language: node_js
node_js:
- '0.10'
notifications:
  email: false
before_script:
- echo -e "Host *.cloudapp.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- test $TRAVIS_BRANCH == "develop" && echo "on develop" && chmod 600 .travis/regex.azure.key
  && eval $(ssh-agent) && ssh-add .travis/regex.azure.key && git remote add deploy-server
  git@regexpress-test.cloudapp.net:/home/git/amber-storm.git && git push --force deploy-server
  $TRAVIS_BRANCH:$TRAVIS_BRANCH
before_install:
- openssl aes-256-cbc -K $encrypted_1d50cdfa274b_key -iv $encrypted_1d50cdfa274b_iv
  -in regex.azure.key.enc -out .travis/regex.azure.key -d
